import { Game } from "@/types/game";

const GameData: Game[] = [
  {
    id: 1,
    title: "UP!",
    description:
      "Stack falling blocks, clear lines, and build quick pattern-recognition skills while you play for good.",
    image: "/images/games/UP_Summer.webp",
    alt: "UP block puzzle game",
    buttonText: "Play Now",
    playLink: "/gameFiles/tetrixGame/index.html",
    category: "Puzzle",
    charity: "community causes",
    playTime: "3 min",
    tags: ["Focus", "Planning", "Classic"],
  },
  {
    id: 2,
    title: "YUM Game",
    description:
      "Match bright treats before the board fills up. Easy to start, quick to replay, and friendly for short sessions.",
    image: "/images/games/YUM_Summer.webp",
    alt: "YUM candy matching game",
    buttonText: "Play Now",
    playLink: "/gameFiles/yumGame/index.html",
    category: "Match",
    charity: "food support",
    playTime: "2 min",
    tags: ["Fast", "Casual", "Color"],
  },
  {
    id: 3,
    title: "POP!",
    description:
      "Aim, pop, and clear bubbles with steady shots. A relaxed arcade challenge that rewards accuracy.",
    image: "/images/games/POP+WATER_AID.webp",
    alt: "POP bubble game for WaterAid",
    buttonText: "Play Now",
    playLink: "/gameFiles/bubbleGame/index.html",
    category: "Arcade",
    charity: "WaterAid",
    playTime: "3 min",
    tags: ["Aim", "Relaxed", "Bubbles"],
  },
  {
    id: 4,
    title: "HISS!",
    description: "Guide the snake, collect points, and avoid crashing as the pace rises.",
    image: "/images/games/HISS+WWF-UK.webp",
    alt: "HISS snake game for WWF",
    buttonText: "Play Now",
    playLink: "/gameFiles/snakeGame/index.html",
    category: "Classic",
    charity: "WWF",
    playTime: "2 min",
    tags: ["Reflex", "Classic", "Survival"],
  },
  {
    id: 5,
    title: "3-2-1!",
    description:
      "Dodge traffic, stay on the road, and push for a longer run in this quick racing challenge.",
    image: "/images/games/321+RED_CROSS.webp",
    alt: "3-2-1 racing game for Red Cross",
    buttonText: "Play Now",
    playLink: "/gameFiles/racingGame/index.html",
    category: "Racing",
    charity: "Red Cross",
    playTime: "2 min",
    tags: ["Speed", "Driving", "Reflex"],
  },
  {
    id: 6,
    title: "Rail Rush!",
    description:
      "Switch lanes, grab coins, and avoid hazards on a fast railway run.",
    image: "/images/games/MORE+MSF.webp",
    alt: "Rail Rush game for MSF",
    buttonText: "Play Now",
    playLink: "/gameFiles/railrushGame/index.html",
    category: "Runner",
    charity: "MSF",
    playTime: "3 min",
    tags: ["Coins", "Lane switch", "Action"],
  },
  {
    id: 7,
    title: "GRRR!",
    description:
      "Move quickly, react to threats, and keep your run alive in a compact arcade challenge.",
    image: "/images/games/GRRR+ALZEIMERS.webp",
    alt: "GRRR arcade game for Alzheimer's Society",
    buttonText: "Play Now",
    playLink: "/gameFiles/grrGame/index.html",
    category: "Action",
    charity: "Alzheimer's Society",
    playTime: "2 min",
    tags: ["Reaction", "Arcade", "Challenge"],
  },
  {
    id: 8,
    title: "FLY!",
    description:
      "Pilot through space, dodge enemies, and keep shooting for a higher score.",
    image: "/images/games/FLY+UNICEF.webp",
    alt: "FLY space shooter game for UNICEF",
    buttonText: "Play Now",
    playLink: "/gameFiles/spaceShotter/index.html",
    category: "Shooter",
    charity: "UNICEF",
    playTime: "4 min",
    tags: ["Space", "Shooter", "Action"],
  },
  {
    id: 10,
    title: "GO!",
    description:
      "Keep moving, make fast choices, and chase a better score with every attempt.",
    image: "/images/games/GO+KIVA.webp",
    alt: "GO game for Kiva",
    buttonText: "Play Now",
    playLink: "/gameFiles/goGame/index.html",
    category: "Quick Play",
    charity: "Kiva",
    playTime: "2 min",
    tags: ["Quick", "Score chase", "Replay"],
  },
];

export default GameData;
